name: CI Python

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [ develop ]

jobs:
  build_lint_test_coverage:
    # Only PRs from feature/* and not drafts
    if: startsWith(github.head_ref, 'feature/') && github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0   # IMPORTANT for Sonar PR analysis / new code metrics

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Ensure test deps available even if not in requirements.txt
          pip install pytest pytest-cov

      - name: Lint with flake8
        run: |
          flake8 src tests --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 src tests --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

      - name: Build wheel
        run: python -m build

      - name: Install built wheel
        run: pip install dist/*.whl

      - name: Run demo (prints & saves outputs)
        run: python src/retail.py

      - name: Pytest with coverage (XML + JUnit for Sonar)
        env:
          PYTHONPATH: src
        run: |
          mkdir -p test-results
          pytest -q \
                 --cov=src \
                 --cov-report=term-missing \
                 --cov-report=xml:coverage.xml \
                 --junitxml=test-results/junit.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # enables PR decoration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload outputs (CSV/JSON)
        uses: actions/upload-artifact@v4
        with:
          name: dq-results
          path: run_outputs/
          if-no-files-found: error

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
          if-no-files-found: error
