name: DB CD to AWS RDS (Liquibase via SSH tunnel)

on:
  push:
    branches: [ develop, main ]
    tags: ['prod-*']
  workflow_dispatch:

env:
  # DB/RDS
  DB_USER: postgres
  DB_NAME: appdb
  DB_PORT: "5432"
  RDS_HOST: cicddemo-1.cxtgit5qkldv.ap-southeast-1.rds.amazonaws.com  # <- same as admin's command
  # SSH tunnel
  LOCAL_DB_PORT: "65432"
  BASTION_HOST: "13.215.152.139"   # <- same as admin's command
  BASTION_USER: "ec2-user"

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # (not strictly needed here since we don't call AWS)

    steps:
      - uses: actions/checkout@v4

      - name: Install clients & tools
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client putty-tools openssh-client netcat-openbsd curl

      # Write the PPK from secret and convert to OpenSSH PEM (OpenSSH can't read .ppk)
      - name: Prepare SSH key from PPK
        env:
          BASTION_PPK: ${{ secrets.BASTION_PPK }}
        run: |
          set -euo pipefail
          test -n "$BASTION_PPK" || (echo "BASTION_PPK secret is empty"; exit 1)
          printf "%s\n" "$BASTION_PPK" > cicddemo.ppk
          chmod 600 cicddemo.ppk
          puttygen cicddemo.ppk -O private-openssh -o cicddemo.pem
          chmod 600 cicddemo.pem

      # Open the same tunnel your admin uses:
      #   ssh -i cicddemo.pem -L 65432:<RDS_HOST>:5432 ec2-user@13.215.152.139
      - name: Open SSH tunnel
        shell: bash
        run: |
          set -euo pipefail
          echo "Opening tunnel 127.0.0.1:${LOCAL_DB_PORT} -> ${RDS_HOST}:${DB_PORT} via ${BASTION_USER}@${BASTION_HOST}"
          ssh -i cicddemo.pem \
              -o StrictHostKeyChecking=no \
              -o ServerAliveInterval=15 \
              -o ExitOnForwardFailure=yes \
              -M -S /tmp/sshtunnel-${GITHUB_RUN_ID} \
              -fnNT -L 127.0.0.1:${LOCAL_DB_PORT}:${RDS_HOST}:${DB_PORT} \
              ${BASTION_USER}@${BASTION_HOST}
          echo "Tunnel up."

      # Quick sanity checks through the tunnel
      - name: Connectivity check (nc + pg_isready)
        env:
          PGPASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: |
          set -e
          nc -vz -w 5 127.0.0.1 "${LOCAL_DB_PORT}" || echo "nc timed out/refused"
          pg_isready -h 127.0.0.1 -p "${LOCAL_DB_PORT}" -U "${DB_USER}" -t 5 || echo "pg_isready not ready yet"

      # Create database if missing (via tunnel)
      - name: Ensure target DB exists
        env:
          PGPASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: |
          set -e
          psql -h 127.0.0.1 -p "${LOCAL_DB_PORT}" -U "${DB_USER}" -d postgres \
               -tc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" | grep -q 1 \
            && echo "Database ${DB_NAME} already exists." \
            || createdb -h 127.0.0.1 -p "${LOCAL_DB_PORT}" -U "${DB_USER}" "${DB_NAME}"

      # Optional least-privilege role (kept; harmless if it already exists)
      - name: Ensure app_readonly role exists
        env:
          PGPASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: |
          psql "postgresql://${{ env.DB_USER }}:${{ secrets.RDS_PASSWORD }}@127.0.0.1:${{ env.LOCAL_DB_PORT }}/${{ env.DB_NAME }}?sslmode=require" \
            -tc "SELECT 1 FROM pg_roles WHERE rolname='app_readonly'" | grep -q 1 \
            || psql "postgresql://${{ env.DB_USER }}:${{ secrets.RDS_PASSWORD }}@127.0.0.1:${{ env.LOCAL_DB_PORT }}/${{ env.DB_NAME }}?sslmode=require" \
                 -c "CREATE ROLE app_readonly;"

      - name: Setup Liquibase
        uses: liquibase/setup-liquibase@v1
        with:
          version: '4.32.0'
          edition: 'oss'

      - name: Liquibase validate
        run: |
          liquibase \
            --url="jdbc:postgresql://127.0.0.1:${{ env.LOCAL_DB_PORT }}/${{ env.DB_NAME }}?sslmode=require" \
            --username="${{ env.DB_USER }}" \
            --password="${{ secrets.RDS_PASSWORD }}" \
            --changeLogFile="db/changelog/master.yaml" \
            --log-level=info \
            validate

      - name: Liquibase update on RDS (via tunnel)
        run: |
          liquibase \
            --url="jdbc:postgresql://127.0.0.1:${{ env.LOCAL_DB_PORT }}/${{ env.DB_NAME }}?sslmode=require" \
            --username="${{ env.DB_USER }}" \
            --password="${{ secrets.RDS_PASSWORD }}" \
            --changeLogFile="db/changelog/master.yaml" \
            --log-level=info \
            update

      - name: Post-deploy SQL (optional)
        env:
          PGPASSWORD: ${{ secrets.RDS_PASSWORD }}
        run: |
          if [ -f db/post_deploy/insert_minimal_data.sql ]; then
            psql -h 127.0.0.1 -p "${{ env.LOCAL_DB_PORT }}" \
                 -U "${{ env.DB_USER }}" -d "${{ env.DB_NAME }}" \
                 -v ON_ERROR_STOP=1 -f db/post_deploy/insert_minimal_data.sql
          fi

      # Close the tunnel cleanly
      - name: Close SSH tunnel
        if: always()
        run: |
          ssh -S /tmp/sshtunnel-${GITHUB_RUN_ID} -O exit ${BASTION_USER}@${BASTION_HOST} || true
